version: "3.7"

services:
  # web server
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # app
      - ./app:/usr/share/nginx/html
      # nginx configs
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      - ./docker/nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      - ./docker/nginx/ca/server.key/:/etc/nginx/server.key:ro
      # logs
      - ./log/nginx:/var/log/nginx

  # php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - "9000"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      # logs
      - ./log/php-fpm:/var/log/php-fpm

  # php-cli
  php-cli:
    build:
      context: .
      dockerfile: ./docker/php-cli/Dockerfile
    volumes:
      - ./app:/usr/share/nginx/html
      - ./config.xml:/usr/share/nginx/html/config.xml
    command: sh -c "composer install && \
                    cd _build && \
                    cp build.config.sample.php build.config.php && \
                    cp build.properties.sample.php build.properties.php && \
                    php transport.core.php && \
                    cd ../setup && \
                    php index.php --installmode=new --config=/usr/share/nginx/html/config.xml"

  # database
  mysql:
    image: mysql:5.7
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=modx
      - MYSQL_USER=modx
      - MYSQL_PASSWORD=modx
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-your_mysql_password}

  pma:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:-100M}
    ports:
      - "8090:80"